export const serviceAdminSession = {
  id: "svc-session-current",
  adminId: "svc-admin-001",
  adminName: "Надя Орлова",
  actorId: "svc-admin-001",
  actorName: "Надя Орлова",
  adminEmail: "service-admin@example.com",
  role: "service_admin",
  authState: "mfa_verified",
  tenantScope: "platform",
  currentTenantId: "tenant-volga",
  allowedActions: [
    "auth.logout",
    "auth.state",
    "billing.read",
    "tenants.read",
    "tenants.manage",
    "billing.change",
    "break-glass.decide",
    "break-glass.request",
    "channels.ingest",
    "channels.read",
    "clients.merge",
    "clients.read",
    "dialogs.manage",
    "dialogs.read",
    "files.read",
    "files.write",
    "flags.read",
    "flags.test",
    "users.support",
    "automation.scenarios.read",
    "automation.scenarios.write",
    "automation.scenarios.archive",
    "automation.scenarios.restore",
    "knowledge.sources.read",
    "knowledge.sources.write",
    "ai.connections.manage",
    "impersonation.stop",
    "incidents.read",
    "knowledge.read",
    "knowledge.write",
    "permissions.read",
    "permissions.validate",
    "platform.alert.acknowledge",
    "platform.alert-routing.write",
    "platform.health-rollups.write",
    "platform.read",
    "platform.telemetry.ingest",
    "quality.manual-reviews.write",
    "quality.ratings.write",
    "quality.scoring-audits.write",
    "presence.read",
    "quotas.check",
    "quotas.read",
    "realtime.events.read",
    "notifications.read",
    "operations.read",
    "operations.write",
    "settings.read",
    "settings.manage",
    "service-admin.users.read",
    "service-admin.users.write",
    "service-admin.audit.read",
    "service-admin.audit.export",
    "security.review",
    "templates.read",
    "templates.write",
    "incidents.manage",
    "flags.manage",
    "impersonation.start"
  ],
  availableOrganizations: [
    { id: "tenant-northstar", name: "Northstar Retail", role: "owner" },
    { id: "tenant-volga", name: "Volga Logistics", role: "admin" },
    { id: "tenant-aurora", name: "Aurora Fintech", role: "owner" },
    { id: "tenant-lumen", name: "Lumen Health", role: "operator" }
  ],
  mfaVerifiedAt: "2026-06-27T07:52:00.000Z",
  expiresAt: "2026-06-27T11:52:00.000Z"
};

export const tenants = [
  {
    id: "tenant-northstar",
    name: "Northstar Retail",
    legalName: "OOO Northstar Retail",
    status: "active",
    planId: "business",
    region: "eu-central",
    owner: "Mira Volkova",
    ownerEmail: "mira@northstar.example",
    workspaces: 8,
    users: 146,
    activeUsers: 91,
    monthlyRevenue: 489000,
    arr: 5868000,
    healthScore: 94,
    sla: 98.7,
    lastSeenAt: "2026-06-27T07:38:00.000Z",
    domains: ["northstar.example", "support.northstar.example"],
    flags: ["ff-ai-replies", "ff-billing-v2"],
    incidentIds: ["inc-search-latency"],
    notes: "Key customer. Billing owner requested a tariff review next week."
  },
  {
    id: "tenant-volga",
    name: "Volga Logistics",
    legalName: "AO Volga Logistics",
    status: "watch",
    planId: "scale",
    region: "ru-west",
    owner: "Sergey Markin",
    ownerEmail: "sergey@volga.example",
    workspaces: 14,
    users: 312,
    activeUsers: 204,
    monthlyRevenue: 1140000,
    arr: 13680000,
    healthScore: 76,
    sla: 91.4,
    lastSeenAt: "2026-06-27T07:31:00.000Z",
    domains: ["volga.example"],
    flags: ["ff-priority-routing"],
    incidentIds: ["inc-webhook-retry"],
    notes: "High webhook volume. Incident notices must remain visible."
  },
  {
    id: "tenant-aurora",
    name: "Aurora Fintech",
    legalName: "Aurora Fintech Group",
    status: "restricted",
    planId: "enterprise",
    region: "eu-west",
    owner: "Elena Moroz",
    ownerEmail: "ops@aurora.example",
    workspaces: 22,
    users: 487,
    activeUsers: 329,
    monthlyRevenue: 2190000,
    arr: 26280000,
    healthScore: 68,
    sla: 86.9,
    lastSeenAt: "2026-06-27T07:25:00.000Z",
    domains: ["aurora.example", "secure.aurora.example"],
    flags: ["ff-ai-replies", "ff-risk-rules"],
    incidentIds: ["inc-auth-degrade", "inc-search-latency"],
    notes: "Restricted after repeated risky admin sessions. Support actions require a reason."
  },
  {
    id: "tenant-lumen",
    name: "Lumen Health",
    legalName: "Lumen Health Ltd",
    status: "trial",
    planId: "starter",
    region: "us-east",
    owner: "Anna Weiss",
    ownerEmail: "admin@lumen.example",
    workspaces: 2,
    users: 24,
    activeUsers: 16,
    monthlyRevenue: 39000,
    arr: 468000,
    healthScore: 89,
    sla: 99.1,
    lastSeenAt: "2026-06-27T07:41:00.000Z",
    domains: ["lumen.example"],
    flags: ["ff-billing-v2"],
    incidentIds: [],
    notes: "Trial ends in 9 days. Candidate for Business tariff."
  }
];

export const tenantUsers = [
  {
    id: "usr-ns-owner",
    tenantId: "tenant-northstar",
    name: "Mira Volkova",
    email: "mira@northstar.example",
    role: "Owner",
    status: "active",
    mfa: "enabled",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-27T07:36:00.000Z",
    sessions: 2,
    risk: "low",
    device: "Chrome, macOS",
    supportNotes: "Primary billing approver."
  },
  {
    id: "usr-ns-agent",
    tenantId: "tenant-northstar",
    name: "Pavel Antonov",
    email: "pavel@northstar.example",
    role: "Senior operator",
    status: "active",
    mfa: "reset_pending",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-27T06:58:00.000Z",
    sessions: 1,
    risk: "medium",
    device: "Edge, Windows",
    supportNotes: "Requested 2FA reset after phone replacement."
  },
  {
    id: "usr-ns-multi",
    tenantId: "tenant-northstar",
    name: "Multi Tenant Operator",
    email: "multi@example.com",
    role: "Senior operator",
    status: "active",
    mfa: "enabled",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-27T07:04:00.000Z",
    sessions: 1,
    risk: "low",
    device: "Chrome, Windows",
    supportNotes: "Shared account fixture for multi-tenant organization selection."
  },
  {
    id: "usr-volga-admin",
    tenantId: "tenant-volga",
    name: "Sergey Markin",
    email: "sergey@volga.example",
    role: "Admin",
    status: "active",
    mfa: "enabled",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-27T07:19:00.000Z",
    sessions: 4,
    risk: "high",
    device: "Chrome, Windows",
    supportNotes: "Four parallel sessions during webhook incident."
  },
  {
    id: "usr-aurora-risk",
    tenantId: "tenant-aurora",
    name: "Elena Moroz",
    email: "ops@aurora.example",
    role: "Owner",
    status: "blocked",
    mfa: "enabled",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-26T21:12:00.000Z",
    sessions: 0,
    risk: "critical",
    device: "Unknown VPN",
    supportNotes: "Blocked after impossible-travel signal."
  },
  {
    id: "usr-lumen-invite",
    tenantId: "tenant-lumen",
    name: "Nikolai R.",
    email: "nikolai@lumen.example",
    role: "Operator",
    status: "invited",
    mfa: "not_configured",
    inviteStatus: "expired",
    lastActiveAt: null,
    sessions: 0,
    risk: "low",
    device: "Device not seen",
    supportNotes: "Needs re-invite before onboarding call."
  },
  {
    id: "usr-lumen-multi",
    tenantId: "tenant-lumen",
    name: "Multi Tenant Operator",
    email: "multi@example.com",
    role: "Senior operator",
    status: "active",
    mfa: "enabled",
    inviteStatus: "accepted",
    lastActiveAt: "2026-06-27T07:02:00.000Z",
    sessions: 1,
    risk: "low",
    device: "Chrome, Windows",
    supportNotes: "Shared account fixture for multi-tenant organization selection."
  }
];

export const permissionRoles = [
  {
    key: "employee",
    description: "Line support operator",
    actions: ["dialogs.read", "templates.read", "templates.write", "clients.read", "presence.write"],
    aliases: ["employee", "operator", "line_1", "line-1", "сотрудник"],
    groupIds: ["line-1"],
    metadata: {}
  },
  {
    key: "senior",
    description: "Senior support operator",
    actions: [
      "dialogs.read",
      "dialogs.manage",
      "panel.read",
      "presence.read",
      "presence.write",
      "routing.read",
      "routing.redistribute",
      "templates.read",
      "templates.write",
      "clients.read",
      "clients.merge",
      "visitors.read",
      "automation.proactive.read",
      "reports.read",
      "reports.export",
      "quality.read",
      "quality.scoring-audits.write",
      "quality.ratings.write",
      "quality.manual-reviews.write",
      "knowledge.read",
      "automation.read",
      "permissions.read",
      "notifications.read",
      "settings.read",
      "employees.passwordReset",
      "outbound.start"
    ],
    aliases: ["senior", "senior_operator", "lead", "старший", "старший сотрудник"],
    groupIds: ["senior-shifts"],
    metadata: {}
  },
  {
    key: "admin",
    description: "Tenant administrator",
    actions: ["*"],
    aliases: ["admin", "administrator", "owner", "админ", "администратор", "владелец"],
    groupIds: ["admins"],
    metadata: {}
  },
  {
    key: "service_admin",
    description: "Platform service administrator",
    actions: Array.from(new Set([
      ...serviceAdminSession.allowedActions,
      "permissions.read",
      "permissions.validate",
      "reports.read",
      "reports.export",
      "reports.write",
      "templates.read",
      "templates.write",
      "knowledge.read",
      "knowledge.write",
      "quality.scoring-audits.write",
      "quality.ratings.write",
      "quality.manual-reviews.write",
      "audit.read",
      "audit.export",
      "audit.redact"
    ])),
    aliases: ["service_admin"],
    groupIds: ["service-admins"],
    metadata: {}
  }
];

export const tariffs = [
  {
    id: "starter",
    name: "Start",
    priceMonthly: 39000,
    includedUsers: 25,
    workspaceLimit: 3,
    retentionDays: 30,
    automationRuns: 20000,
    features: ["Shared inbox", "Basic reports", "Email support"],
    changePolicy: "Immediate downgrade is available during trial only."
  },
  {
    id: "business",
    name: "Business",
    priceMonthly: 129000,
    includedUsers: 150,
    workspaceLimit: 10,
    retentionDays: 180,
    automationRuns: 150000,
    features: ["SLA routing", "AI suggestions", "Audit export", "Priority support"],
    changePolicy: "Changes apply next billing period unless explicitly confirmed."
  },
  {
    id: "scale",
    name: "Scale",
    priceMonthly: 380000,
    includedUsers: 350,
    workspaceLimit: 20,
    retentionDays: 365,
    automationRuns: 600000,
    features: ["Webhook replay", "Advanced routing", "Feature flags", "Dedicated CSM"],
    changePolicy: "Requires reason and billing approval preview."
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: 990000,
    includedUsers: 700,
    workspaceLimit: 40,
    retentionDays: 1095,
    automationRuns: 2500000,
    features: ["SAML", "Regional data storage", "Custom limits", "Incident bridge 24/7"],
    changePolicy: "Requires written confirmation and service-admin audit."
  }
];

export const incidents = [
  {
    id: "inc-webhook-retry",
    title: "Webhook retry queue above threshold",
    status: "investigating",
    severity: "sev2",
    componentId: "cmp-webhooks",
    owner: "Integration on-call",
    startedAt: "2026-06-27T06:55:00.000Z",
    updatedAt: "2026-06-27T07:34:00.000Z",
    affectedTenantIds: ["tenant-volga"],
    impact: "Delayed delivery for high-load webhook endpoints in ru-west.",
    customerMessage: "Webhook delivery is delayed. Events are queued and will retry.",
    updates: [
      { at: "07:34", author: "on-call", text: "Started failed queue cleanup for Volga endpoints." },
      { at: "07:12", author: "support", text: "Incident linked to Volga account timeline." }
    ]
  },
  {
    id: "inc-auth-degrade",
    title: "Elevated 2FA verification latency",
    status: "monitoring",
    severity: "sev3",
    componentId: "cmp-auth",
    owner: "Identity on-call",
    startedAt: "2026-06-27T07:05:00.000Z",
    updatedAt: "2026-06-27T07:42:00.000Z",
    affectedTenantIds: ["tenant-aurora"],
    impact: "Service admins can wait longer for session review and 2FA reset.",
    customerMessage: "Authorization is available with elevated latency.",
    updates: [
      { at: "07:42", author: "identity", text: "Latency returned below alert threshold." },
      { at: "07:21", author: "risk", text: "No new impossible-travel alerts." }
    ]
  },
  {
    id: "inc-search-latency",
    title: "Conversation search index lag",
    status: "identified",
    severity: "sev3",
    componentId: "cmp-search",
    owner: "Search and data",
    startedAt: "2026-06-27T06:44:00.000Z",
    updatedAt: "2026-06-27T07:28:00.000Z",
    affectedTenantIds: ["tenant-northstar", "tenant-aurora"],
    impact: "New messages may appear in search with up to 14 minutes delay.",
    customerMessage: "Conversation search is delayed; live chats are not affected.",
    updates: [
      { at: "07:28", author: "data", text: "Backfill reached 71%." },
      { at: "06:58", author: "support", text: "Added status note for Northstar." }
    ]
  }
];

export const featureFlags = [
  {
    id: "flag-ai-agents-v1",
    key: "ai_agents_v1",
    name: "AI agents v1",
    status: "on",
    environment: "production",
    scope: "tenant",
    rollout: 0,
    owner: "AI team",
    segments: [],
    enabledTenantIds: ["tenant-local-001"],
    variants: [{ id: "rollout", weight: 100 }],
    killSwitch: true,
    updatedAt: "2026-07-12T00:00:00.000Z"
  },
  {
    id: "flag-ai-bots",
    key: "ai_bots",
    name: "AI consultation bots",
    status: "off",
    environment: "production",
    scope: "tenant",
    rollout: 0,
    owner: "AI team",
    segments: [],
    enabledTenantIds: [],
    variants: [{ id: "disabled", weight: 100 }],
    killSwitch: true,
    updatedAt: "2026-07-12T00:00:00.000Z"
  },
  {
    id: "flag-ai-bot-mcp-sources",
    key: "ai_bot_mcp_sources",
    name: "AI bot MCP knowledge sources",
    status: "off",
    environment: "production",
    scope: "tenant",
    rollout: 0,
    owner: "AI team",
    segments: [],
    enabledTenantIds: [],
    variants: [{ id: "disabled", weight: 100 }],
    killSwitch: true,
    updatedAt: "2026-07-12T00:00:00.000Z"
  },
  {
    id: "flag-ai-replies",
    key: "ff-ai-replies",
    name: "AI reply assistant",
    status: "on",
    environment: "production",
    scope: "tenant",
    rollout: 72,
    owner: "AI team",
    segments: ["business", "enterprise"],
    enabledTenantIds: ["tenant-northstar", "tenant-aurora"],
    variants: [
      { id: "control", weight: 28 },
      { id: "assistant-v2", weight: 72 }
    ],
    killSwitch: true,
    updatedAt: "2026-06-27T06:30:00.000Z"
  },
  {
    id: "flag-billing-v2",
    key: "ff-billing-v2",
    name: "Tariff billing v2",
    status: "gradual",
    environment: "production",
    scope: "plan",
    rollout: 35,
    owner: "Billing",
    segments: ["starter", "business"],
    enabledTenantIds: ["tenant-northstar", "tenant-lumen"],
    variants: [
      { id: "legacy", weight: 65 },
      { id: "tariff-preview", weight: 35 }
    ],
    killSwitch: true,
    updatedAt: "2026-06-27T05:54:00.000Z"
  },
  {
    id: "flag-priority-routing",
    key: "ff-priority-routing",
    name: "Priority routing engine",
    status: "on",
    environment: "production",
    scope: "tenant",
    rollout: 100,
    owner: "Routing",
    segments: ["scale", "enterprise"],
    enabledTenantIds: ["tenant-volga", "tenant-aurora"],
    variants: [{ id: "enabled", weight: 100 }],
    killSwitch: false,
    updatedAt: "2026-06-26T19:12:00.000Z"
  },
  {
    id: "flag-risk-rules",
    key: "ff-risk-rules",
    name: "Adaptive risk rules",
    status: "guarded",
    environment: "production",
    scope: "tenant",
    rollout: 18,
    owner: "Identity",
    segments: ["enterprise"],
    enabledTenantIds: ["tenant-aurora"],
    variants: [
      { id: "baseline", weight: 82 },
      { id: "adaptive", weight: 18 }
    ],
    killSwitch: true,
    updatedAt: "2026-06-27T07:10:00.000Z"
  }
];

export const tenantAuditEvents = [
  {
    id: "svc-audit-1001",
    at: "2026-06-27T07:42:00.000Z",
    actor: "Nadya Orlova",
    action: "incident.monitor",
    target: "inc-auth-degrade",
    tenantId: "tenant-aurora",
    severity: "info",
    reason: "Monitoring identity recovery after risk rule update",
    result: "ok",
    traceId: "trc_service_admin_incident_1001"
  },
  {
    id: "svc-audit-1002",
    at: "2026-06-27T07:34:00.000Z",
    actor: "Nadya Orlova",
    action: "user.block",
    target: "usr-aurora-risk",
    tenantId: "tenant-aurora",
    severity: "critical",
    reason: "Support confirmed impossible-travel signal",
    result: "ok",
    traceId: "trc_service_admin_user_1002"
  },
  {
    id: "svc-audit-1003",
    at: "2026-06-27T07:20:00.000Z",
    actor: "Billing Ops",
    action: "tariff.preview",
    target: "tenant-lumen",
    tenantId: "tenant-lumen",
    severity: "info",
    reason: "Trial conversion estimate",
    result: "ok",
    traceId: "trc_service_admin_billing_1003"
  },
  {
    id: "svc-audit-1004",
    at: "2026-06-27T07:12:00.000Z",
    actor: "Nadya Orlova",
    action: "impersonation.start",
    target: "tenant-volga",
    tenantId: "tenant-volga",
    severity: "warn",
    reason: "Customer approved webhook retry investigation",
    result: "ok",
    traceId: "trc_service_admin_impersonation_1004"
  }
];
