BORG_REPO=ssh://ruvdsbackup@95.31.2.38:22/./repository
BORG_PASSPHRASE_FILE=/root/.config/borg/ruvds-passphrase
BORG_RSH="ssh -i /root/.ssh/id_ed25519_ruvds_backup -o BatchMode=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/root/.ssh/known_hosts_ruvds_backup -o ServerAliveInterval=30 -o ServerAliveCountMax=3"
