INSERT INTO "notifications" (
    "id",
    "tenant_id",
    "recipient_user_id",
    "category",
    "type",
    "type_key",
    "title",
    "detail",
    "meta",
    "action",
    "action_target",
    "tone",
    "history",
    "read_at",
    "created_at"
) VALUES
(
    'notif-sla-vladimir',
    'tenant-volga',
    NULL,
    'sla_risk',
    'SLA',
    'sla',
    'Владимир Б. без тематики',
    'Закрытие заблокировано, SLA просрочен',
    'Telegram · очередь спасения',
    'Открыть диалог',
    NULL,
    'danger',
    '11:36 · SLA alert доставлен старшему сотруднику',
    NULL,
    '2026-07-02T08:36:00.000Z'::timestamptz
),
(
    'notif-mention-anna',
    'tenant-volga',
    NULL,
    'invite_event',
    'Mention',
    'mention',
    'Анна Р. упомянула вас',
    'Нужна проверка возврата до закрытия',
    'MAX · старший сотрудник',
    'Посмотреть',
    NULL,
    'warn',
    '11:34 · mention из внутреннего комментария',
    NULL,
    '2026-07-02T08:34:00.000Z'::timestamptz
),
(
    'notif-channel-vk',
    'tenant-volga',
    NULL,
    'channel_failure',
    'Channel',
    'channel',
    'VK: рост ошибок webhook',
    '3 ошибки доставки за последние 15 минут',
    'Интеграции · требует администратора',
    'Открыть канал',
    NULL,
    'info',
    '11:31 · webhook retry превысил порог',
    NULL,
    '2026-07-02T08:31:00.000Z'::timestamptz
),
(
    'notif-export-ready',
    'tenant-volga',
    NULL,
    'export_completion',
    'Export',
    'export',
    'Ежедневный отчет готов',
    'XLSX, 486 строк, audit export-2418',
    'Отчеты · сегодня 11:30',
    'Скачать',
    jsonb_build_object(
        'fileName', 'export-2418.xlsx',
        'format', 'XLSX',
        'jobId', 'export-2418',
        'kind', 'download',
        'service', 'reports'
    ),
    'ok',
    '11:30 · export queue завершила задачу',
    NULL,
    '2026-07-02T08:30:00.000Z'::timestamptz
),
(
    'notif-ladoga-sla',
    'tenant-ladoga',
    NULL,
    'sla_risk',
    'SLA',
    'sla',
    'Очередь Ladoga перегружена',
    'SLA risk на 4 диалогах',
    'Telegram · rescue queue',
    'Открыть панель',
    NULL,
    'danger',
    '10:12 · SLA risk escalated',
    NULL,
    '2026-07-02T07:12:00.000Z'::timestamptz
),
(
    'notif-privileged-admin',
    'tenant-volga',
    NULL,
    'privileged_admin',
    'Privileged',
    'privileged',
    'Service-admin audit export готов',
    'CSV, 128 событий, redaction policy applied',
    'Service admin · privileged',
    'Открыть audit',
    NULL,
    'info',
    '09:55 · privileged export completed',
    '2026-07-02T09:56:00.000Z'::timestamptz,
    '2026-07-02T06:55:00.000Z'::timestamptz
)
ON CONFLICT ("id") DO UPDATE SET
    "tenant_id" = EXCLUDED."tenant_id",
    "recipient_user_id" = EXCLUDED."recipient_user_id",
    "category" = EXCLUDED."category",
    "type" = EXCLUDED."type",
    "type_key" = EXCLUDED."type_key",
    "title" = EXCLUDED."title",
    "detail" = EXCLUDED."detail",
    "meta" = EXCLUDED."meta",
    "action" = EXCLUDED."action",
    "action_target" = EXCLUDED."action_target",
    "tone" = EXCLUDED."tone",
    "history" = EXCLUDED."history",
    "read_at" = COALESCE("notifications"."read_at", EXCLUDED."read_at"),
    "created_at" = EXCLUDED."created_at";
