import type { BillingTariff } from "./billing.types.js";

export const billingTariffCatalog: BillingTariff[] = [
  {
    id: "free",
    name: "Free",
    billingAvailability: "free",
    priceMonthly: 0,
    includedUsers: 1,
    ownerOnly: true,
    workspaceLimit: 1,
    webhookLimit: 0,
    storageGb: 1,
    retentionDays: 7,
    automationRuns: 0,
    aiTokens: 0,
    botRuns: 0,
    reportExports: 3,
    features: ["shared-inbox", "website-chat", "email-support"],
    changePolicy: "self_service_upgrade"
  },
  {
    id: "starter",
    name: "Starter",
    billingAvailability: "paid",
    priceMonthly: 39000,
    includedUsers: 3,
    ownerOnly: false,
    workspaceLimit: 3,
    webhookLimit: 20000,
    storageGb: 50,
    retentionDays: 30,
    automationRuns: 5000,
    aiTokens: 250000,
    botRuns: 2500,
    reportExports: 25,
    features: ["shared-inbox", "basic-analytics", "email-support"],
    changePolicy: "manager_confirmation_required"
  },
  {
    id: "business",
    name: "Business",
    billingAvailability: "paid",
    priceMonthly: 129000,
    includedUsers: 15,
    ownerOnly: false,
    workspaceLimit: 10,
    webhookLimit: 150000,
    storageGb: 300,
    retentionDays: 180,
    automationRuns: 50000,
    aiTokens: 2000000,
    botRuns: 25000,
    reportExports: 250,
    features: ["omnichannel", "routing", "sla", "exports"],
    changePolicy: "manager_confirmation_required"
  },
  {
    id: "scale",
    name: "Scale",
    billingAvailability: "paid",
    priceMonthly: 380000,
    includedUsers: 35,
    ownerOnly: false,
    workspaceLimit: 20,
    webhookLimit: 600000,
    storageGb: 1000,
    retentionDays: 365,
    automationRuns: 250000,
    aiTokens: 7000000,
    botRuns: 120000,
    reportExports: 1000,
    features: ["advanced-automation", "quality-ai", "custom-integrations"],
    changePolicy: "manager_confirmation_required"
  },
  {
    id: "enterprise",
    name: "Enterprise",
    billingAvailability: "paid",
    priceMonthly: 990000,
    includedUsers: 70,
    ownerOnly: false,
    workspaceLimit: 40,
    webhookLimit: 2500000,
    storageGb: 5000,
    retentionDays: 730,
    automationRuns: 1000000,
    aiTokens: 25000000,
    botRuns: 500000,
    reportExports: 5000,
    features: ["sso", "dedicated-success", "data-residency", "custom-sla"],
    changePolicy: "dual_approval_required"
  }
];
